[phases.setup]
nixPkgs = ["python311", "uv", "nodejs", "pnpm"]

[phases.install]
cmds = [
    "if [ \"$APP_TYPE\" = \"frontend\" ]; then cd frontend && pnpm install; else cd api && uv sync --no-dev --frozen; fi"
]

[phases.build]
cmds = [
    "if [ \"$APP_TYPE\" = \"frontend\" ]; then cd frontend && NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL} pnpm run build; fi"
]

[start]
cmd = "if [ \"$APP_TYPE\" = \"frontend\" ]; then sh /app/start_frontend.sh; else sh /app/start_backend.sh; fi"
